/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coreutils;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int font = 0x7f0300ce;
        public static final int fontProviderAuthority = 0x7f0300d0;
        public static final int fontProviderCerts = 0x7f0300d1;
        public static final int fontProviderFetchStrategy = 0x7f0300d2;
        public static final int fontProviderFetchTimeout = 0x7f0300d3;
        public static final int fontProviderPackage = 0x7f0300d4;
        public static final int fontProviderQuery = 0x7f0300d5;
        public static final int fontStyle = 0x7f0300d6;
        public static final int fontWeight = 0x7f0300d7;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050051;
        public static final int notification_icon_bg_color = 0x7f050052;
        public static final int ripple_material_light = 0x7f050063;
        public static final int secondary_text_default_material_light = 0x7f050065;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060050;
        public static final int compat_button_inset_vertical_material = 0x7f060051;
        public static final int compat_button_padding_horizontal_material = 0x7f060052;
        public static final int compat_button_padding_vertical_material = 0x7f060053;
        public static final int compat_control_corner_material = 0x7f060054;
        public static final int notification_action_icon_size = 0x7f06008a;
        public static final int notification_action_text_size = 0x7f06008b;
        public static final int notification_big_circle_margin = 0x7f06008c;
        public static final int notification_content_margin_start = 0x7f0600